version: '3.7'

services:
  nginx-puma:
    container_name: snibox-nginx
    image: juanico/nginx-puma:snibox
    restart: unless-stopped
    volumes:
      - '/patch/to/data/data:/var/www/html'
      - '/patch/to/data/nginx:/etc/nginx'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '/patch/to/data/certs:/etc/nginx/certs'
    depends_on:
      - backend
    ports:
        - '443:443'
  
  backend:
    container_name: snibox-backend
    image: juanico/snibox:latest
    volumes:
        - '/patch/to/data/data/app/db:/app/db/database'
    restart: unless-stopped
    env_file:
        - .env
    depends_on:
      - backend-cache
    security_opt:
      - no-new-privileges:true
 
  backend-cache:
    image: redis:alpine
    container_name: snibox-redis
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
